import { ScrollView, StyleSheet, Text, View } from 'react-native';
import { useRouter } from 'expo-router';
import { ArrowLeft } from 'lucide-react-native';
import { TouchableOpacity } from 'react-native';
import { useSettings } from '../utils/settings';

const privacyPolicyContent = `# Privacy Policy

**Effective Date:** December 8, 2024
**Last Updated:** December 8, 2024

## Introduction

Iron Faith ("we," "our," or "us") is committed to protecting your privacy. This Privacy Policy explains how we collect, use, and safeguard your personal information when you use our mobile application.

## Information We Collect

### Account Information
• Email address (for account creation and authentication)
• Password (encrypted and securely stored)
• User profile data (name, bio, preferences)

### Usage Data
• Conversation history with our AI assistant
• Chat messages and responses
• User preferences and settings
• Bible study notes and bookmarks (if applicable)

### Automatically Collected Information
• Device information (device type, operating system)
• App usage statistics
• Error logs and crash reports

## How We Use Your Information

We use your information to:
• Provide and maintain the Iron Faith service
• Authenticate your account and secure your data
• Generate AI-powered Bible study responses
• Personalize your experience based on preferences
• Improve our app and develop new features
• Send important service updates and notifications

## Data Storage and Security

### Third-Party Services

**Supabase (Database & Authentication)**
• All user data is stored securely with Supabase
• Data is encrypted in transit and at rest
• Located in secure data centers
• Subject to Supabase's privacy policy

**OpenAI (AI Responses)**
• Your questions are sent to OpenAI's API to generate responses
• OpenAI processes queries but does not store conversation history
• Data transmission is encrypted
• Subject to OpenAI's privacy policy and data usage terms

### Security Measures
• Industry-standard encryption (TLS/SSL)
• Secure authentication with hashed passwords
• Row-level security policies to isolate user data
• Regular security audits and updates

## Your Data Rights

You have the right to:
• Access your personal data
• Update or correct your information
• Delete your account and associated data
• Export your conversation history
• Opt out of certain data collection

To exercise these rights, please contact us through the app settings or via email.

## Data Retention

• Active account data is retained while your account exists
• Deleted conversations are permanently removed from our database
• Account deletion removes all associated personal data within 30 days
• Anonymized usage statistics may be retained for analytics

## Children's Privacy

Iron Faith is not intended for children under 13. We do not knowingly collect personal information from children under 13. If you believe we have inadvertently collected such information, please contact us immediately.

## AI-Generated Content Disclaimer

Responses generated by our AI assistant are for educational and informational purposes only. They should not be considered as professional theological advice, counseling, or official church doctrine. Always consult with qualified religious leaders for important spiritual matters.

## Changes to This Privacy Policy

We may update this Privacy Policy from time to time. We will notify you of significant changes by:
• Posting the new Privacy Policy in the app
• Updating the "Last Updated" date
• Sending you a notification (if you're a registered user)

Your continued use of Iron Faith after changes indicates acceptance of the updated policy.

## International Data Transfers

Your data may be transferred to and processed in countries other than your country of residence. We ensure appropriate safeguards are in place to protect your data in compliance with applicable laws.

## Contact Us

If you have questions, concerns, or requests regarding this Privacy Policy or your personal data:

**Email:** support@ironfaith.app
**App:** Use the "Contact Support" option in Settings

## Your Consent

By using Iron Faith, you consent to the collection and use of your information as described in this Privacy Policy.`;

export default function PrivacyPolicyScreen() {
  const router = useRouter();
  const { theme } = useSettings();

  return (
    <View style={[styles.container, { backgroundColor: theme.background }]}>
      <View style={[styles.header, { backgroundColor: theme.background, borderBottomColor: theme.border }]}>
        <TouchableOpacity
          style={styles.backButton}
          onPress={() => router.back()}
        >
          <ArrowLeft size={24} color={theme.text} />
        </TouchableOpacity>
        <Text style={[styles.headerTitle, { color: theme.text }]}>Privacy Policy</Text>
        <View style={styles.placeholder} />
      </View>

      <ScrollView
        style={styles.scrollView}
        contentContainerStyle={styles.content}
      >
        <Text style={[styles.text, { color: theme.text }]}>{privacyPolicyContent}</Text>
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    paddingTop: 60,
    borderBottomWidth: 1,
  },
  backButton: {
    padding: 8,
    marginLeft: -8,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '600',
  },
  placeholder: {
    width: 40,
  },
  scrollView: {
    flex: 1,
  },
  content: {
    padding: 20,
  },
  text: {
    fontSize: 15,
    lineHeight: 24,
  },
});
